name: Frontend CI - Streamlit 

on:
 push:
   branches: ["main"]
   paths:
      - "Frontend/**"

jobs:
  frontend-test:
    runs-on: ubuntu-latest 

    steps:
     - name: Checkout repository 
       uses: actions/checkout@v4

     - name: set up python 
       uses: actions/setup-python@sv5
       with:
        python-version: "3.10"

     - name: Install frontend dependencies
       run: |
         cd frontend
         pip install --upgrade pip 
         pip install -r requirements.txt 

     - name: Streamlit import checks 
       run: |
         cd frontend
          python -c "import streamlit"
          python -c "import streamlit_app"
          
